spring.application.name=chroniques-de-tyrie-back
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/chroniques_de_tyrie

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

logging.level.org.springframework.security=DEBUG

media.storage.root-directory=${MEDIA_STORAGE_ROOT}

media.avatar.max-file-size=5MB
media.avatar.max-width=512
media.avatar.max-height=512
media.avatar.max-pixel-count=40000000
media.avatar.webp-quality=0.85

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB