spring.application.name=chroniques-de-tyrie-back
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/chroniques_de_tyrie

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true